<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>


		<!-- NuGet package metadata -->
		<PackageId>JwtRefreshTokenRotation</PackageId>
		<Version>1.1.0</Version>
		<Authors>Abu Habibah</Authors>
		<!--<Company></Company>-->
		<Description>ASP.NET Core middleware for JWT inactivity threshold enforcement with Redis-backed tracking.</Description>
		<PackageTags>jwt;middleware;redis;aspnetcore;security;authentication</PackageTags>
		<RepositoryUrl>https://github.com/Abu-Habibah/JwtRefreshTokenRotation.V1</RepositoryUrl>
		<PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Title>JwtRefreshTokenRotation</Title>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="JwtTokenGeneratorX.cs" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="..\README.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.1" />
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.1" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.1" />
		<PackageReference Include="StackExchange.Redis" Version="2.10.1" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
	</ItemGroup>

</Project>
