name: .NET Publish

on:
  push:
    tags:
      - 'v*.0.0'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - run: dotnet restore
      - run: dotnet build TokenSharp/TokenSharp.csproj --configuration Release
      - run: dotnet pack TokenSharp/TokenSharp.csproj --configuration Release -o ./artifacts
      - run: dotnet nuget push ./artifacts/**/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      - run: dotnet nuget push ./artifacts/**/*.nupkg --api-key ${{ secrets.GH_PUBLISH_PACKAGE }} --source "https://nuget.pkg.github.com/Abu-Habibah/index.json" --skip-duplicate
